[project]
name = "blank-app-template"
version = "0.1.0"
description = "A simple Streamlit app template."
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "psycopg2-binary>=2.9.12",
    "sqlalchemy>=2.0.51",
    "streamlit>=1.60.0",
    "streamlit-calendar>=1.4.0",
    "supabase>=2.31.0",
    "sqlalchemy-libsql",
]

[tool.uv]
package = false
