name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 21 * * *'  # 한국시간 06:00
    - cron: '0 3 * * *'   # 한국시간 12:00 (낮 12시)
    - cron: '0 9 * * *'   # 한국시간 18:00 (오후 6시)
    - cron: '0 15 * * *'  # 한국시간 00:00 (자정)
  workflow_dispatch:       # 필요하면 Actions 탭에서 수동으로도 실행 가능

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: 사이트 접속해서 깨우기
        run: |
          curl -sS -o /dev/null -w "응답 코드: %{http_code}\n" https://consmanager.streamlit.app/